import { TerraformFile, EditorStatus } from './types';

// Mock Terraform files for development testing
export const MOCK_TERRAFORM_FILES: TerraformFile[] = [
  {
    id: 'main-tf',
    name: 'main.tf',
    type: 'main',
    language: 'hcl',
    content: `# Generated by Terraport Engine v2.4
# Target: Nutanix Cloud Platform (NCP)
# Session ID: sess_abc123

terraform {
  required_version = ">= 1.0.0"
  required_providers {
    nutanix = {
      source  = "nutanix/nutanix"
      version = "~> 1.9.0"
    }
  }
}

# Web Server Production VM
resource "nutanix_virtual_machine" "web_server_prod" {
  name                 = "web-srv-01"
  cluster_uuid         = var.nutanix_cluster_uuid
  num_vcpus_per_socket = 2
  num_sockets          = 1
  memory_size_mib      = 4096

  guest_customization_cloud_init_user_data = base64encode(
    file("\${path.module}/init.yaml")
  )

  nic_list {
    subnet_uuid = var.subnet_uuid_dmz
  }

  disk_list {
    data_source_reference = {
      kind = "image"
      uuid = var.image_uuid_ubuntu
    }
    device_properties {
      disk_address = {
        device_index = 0
        adapter_type = "SCSI"
      }
      device_type = "DISK"
    }
  }

  categories {
    name  = "Environment"
    value = "Production"
  }

  categories {
    name  = "AppTier"
    value = "Web"
  }
}

# Application Server VM
resource "nutanix_virtual_machine" "app_server_prod" {
  name                 = "app-srv-01"
  cluster_uuid         = var.nutanix_cluster_uuid
  num_vcpus_per_socket = 4
  num_sockets          = 2
  memory_size_mib      = 16384

  nic_list {
    subnet_uuid = var.subnet_uuid_app
  }

  disk_list {
    data_source_reference = {
      kind = "image"
      uuid = var.image_uuid_ubuntu
    }
    device_properties {
      disk_address = {
        device_index = 0
        adapter_type = "SCSI"
      }
      device_type = "DISK"
    }
    disk_size_mib = 102400
  }

  categories {
    name  = "Environment"
    value = "Production"
  }

  categories {
    name  = "AppTier"
    value = "Application"
  }
}

# Database Server VM
resource "nutanix_virtual_machine" "db_server_prod" {
  name                 = "db-srv-01"
  cluster_uuid         = var.nutanix_cluster_uuid
  num_vcpus_per_socket = 4
  num_sockets          = 2
  memory_size_mib      = 32768

  nic_list {
    subnet_uuid = var.subnet_uuid_db
  }

  disk_list {
    data_source_reference = {
      kind = "image"
      uuid = var.image_uuid_ubuntu
    }
    device_properties {
      disk_address = {
        device_index = 0
        adapter_type = "SCSI"
      }
      device_type = "DISK"
    }
    disk_size_mib = 512000
  }

  categories {
    name  = "Environment"
    value = "Production"
  }

  categories {
    name  = "AppTier"
    value = "Database"
  }
}
`,
  },
  {
    id: 'variables-tf',
    name: 'variables.tf',
    type: 'variables',
    language: 'hcl',
    content: `# Variables for Nutanix infrastructure
# Generated by Terraport Engine v2.4

# Cluster Configuration
variable "nutanix_cluster_uuid" {
  description = "UUID of the Nutanix cluster"
  type        = string
}

variable "prism_central_endpoint" {
  description = "Prism Central API endpoint"
  type        = string
}

variable "prism_central_username" {
  description = "Prism Central username"
  type        = string
  sensitive   = true
}

variable "prism_central_password" {
  description = "Prism Central password"
  type        = string
  sensitive   = true
}

# Network Configuration
variable "subnet_uuid_dmz" {
  description = "UUID of the DMZ subnet"
  type        = string
}

variable "subnet_uuid_app" {
  description = "UUID of the Application subnet"
  type        = string
}

variable "subnet_uuid_db" {
  description = "UUID of the Database subnet"
  type        = string
}

# Image Configuration
variable "image_uuid_ubuntu" {
  description = "UUID of the Ubuntu 22.04 LTS image"
  type        = string
}

variable "image_uuid_centos" {
  description = "UUID of the CentOS 8 image"
  type        = string
  default     = ""
}

# Tags and Categories
variable "environment" {
  description = "Environment name (Production, Staging, Development)"
  type        = string
  default     = "Production"
}

variable "project_name" {
  description = "Project name for resource tagging"
  type        = string
  default     = "Terraport Migration"
}
`,
  },
  {
    id: 'outputs-tf',
    name: 'outputs.tf',
    type: 'outputs',
    language: 'hcl',
    content: `# Outputs for Nutanix infrastructure
# Generated by Terraport Engine v2.4

output "web_server_uuid" {
  description = "UUID of the web server VM"
  value       = nutanix_virtual_machine.web_server_prod.id
}

output "web_server_ip" {
  description = "IP address of the web server VM"
  value       = nutanix_virtual_machine.web_server_prod.nic_list[0].ip_endpoint_list[0].ip
}

output "app_server_uuid" {
  description = "UUID of the application server VM"
  value       = nutanix_virtual_machine.app_server_prod.id
}

output "app_server_ip" {
  description = "IP address of the application server VM"
  value       = nutanix_virtual_machine.app_server_prod.nic_list[0].ip_endpoint_list[0].ip
}

output "db_server_uuid" {
  description = "UUID of the database server VM"
  value       = nutanix_virtual_machine.db_server_prod.id
}

output "db_server_ip" {
  description = "IP address of the database server VM"
  value       = nutanix_virtual_machine.db_server_prod.nic_list[0].ip_endpoint_list[0].ip
}

output "migration_summary" {
  description = "Summary of migrated resources"
  value = {
    total_vms      = 3
    total_vcpus    = 14
    total_memory   = "52 GB"
    source_region  = "us-east-1"
    target_cluster = var.nutanix_cluster_uuid
  }
}
`,
  },
  {
    id: 'provider-tf',
    name: 'provider.tf',
    type: 'provider',
    language: 'hcl',
    content: `# Nutanix Provider Configuration
# Generated by Terraport Engine v2.4

provider "nutanix" {
  username     = var.prism_central_username
  password     = var.prism_central_password
  endpoint     = var.prism_central_endpoint
  insecure     = true
  wait_timeout = 60
}

# Provider alias for secondary cluster (if needed)
# provider "nutanix" {
#   alias        = "secondary"
#   username     = var.prism_central_username
#   password     = var.prism_central_password
#   endpoint     = var.secondary_pc_endpoint
#   insecure     = true
#   wait_timeout = 60
# }
`,
  },
  {
    id: 'terraform-tfvars',
    name: 'terraform.tfvars',
    type: 'tfvars',
    language: 'hcl',
    content: `# Terraform Variables File
# Generated by Terraport Engine v2.4
#
# IMPORTANT: Update these values before applying!
# Do not commit sensitive values to version control.

# Cluster Configuration
nutanix_cluster_uuid   = "00000000-0000-0000-0000-000000000000"
prism_central_endpoint = "https://prism-central.example.com:9440"

# Network Configuration (UUIDs from Prism Central)
subnet_uuid_dmz = "11111111-1111-1111-1111-111111111111"
subnet_uuid_app = "22222222-2222-2222-2222-222222222222"
subnet_uuid_db  = "33333333-3333-3333-3333-333333333333"

# Image Configuration (UUIDs from Image Service)
image_uuid_ubuntu = "44444444-4444-4444-4444-444444444444"
image_uuid_centos = "55555555-5555-5555-5555-555555555555"

# Tags and Categories
environment  = "Production"
project_name = "AWS to Nutanix Migration"

# Note: Sensitive values (username/password) should be provided via:
# - Environment variables: TF_VAR_prism_central_username, TF_VAR_prism_central_password
# - Or via a separate .tfvars file that is git-ignored
# - Or via HashiCorp Vault or other secrets management
`,
  },
];

// Default editor status
export const DEFAULT_EDITOR_STATUS: EditorStatus = {
  ready: true,
  errors: 0,
  warnings: 0,
  line: 1,
  column: 1,
  encoding: 'UTF-8',
  language: 'Terraform',
};

// File icon colors based on type
export const FILE_ICON_COLORS: Record<string, string> = {
  main: 'var(--color-text-warning)', // amber for main.tf
  variables: 'var(--color-text-link)', // blue for variables
  outputs: 'var(--color-text-success)', // green for outputs
  provider: 'var(--color-text-brand)', // brand color for provider
  tfvars: 'var(--color-text-tertiary-paragraph)', // gray for tfvars
};
