import { SecurityIssue } from './types';

export const MOCK_SECURITY_ISSUES: SecurityIssue[] = [
  {
    id: 'sec-001',
    title: 'Over-permissive Security Group (0.0.0.0/0 on 80/443)',
    description: 'Web tier allows inbound HTTP/HTTPS from the entire internet. This massively expands attack surface and invites brute force, exploit scanning, and bot traffic.',
    severity: 'critical',
    category: 'overly_permissive',
    status: 'pending',
    affectedResource: {
      id: 'sg-0f2e1d4c',
      type: 'security_group',
      name: 'Web-Tier',
      region: 'us-east-1',
    },
    recommendation: 'Restrict inbound rules to specific IP ranges or use a WAF/Load Balancer to filter traffic before reaching your instances.',
    details: [
      'Port 80 (HTTP) open to 0.0.0.0/0',
      'Port 443 (HTTPS) open to 0.0.0.0/0',
      'All outbound traffic allowed',
    ],
    riskScore: 95,
  },
  {
    id: 'sec-002',
    title: 'SSH Port Exposed to Internet',
    description: 'Security group allows SSH (port 22) access from any IP address. This is a common attack vector for brute force attempts and unauthorized access.',
    severity: 'critical',
    category: 'public_exposure',
    status: 'pending',
    affectedResource: {
      id: 'sg-0a3b4c5d',
      type: 'security_group',
      name: 'DB-Tier',
      region: 'us-east-1',
    },
    recommendation: 'Restrict SSH access to specific trusted IP addresses or use a bastion host / VPN for secure access.',
    details: [
      'Port 22 (SSH) open to 0.0.0.0/0',
      'No network ACL restrictions in place',
    ],
    riskScore: 92,
  },
  {
    id: 'sec-003',
    title: 'Unencrypted EBS Volume',
    description: 'EBS volume attached to production database is not encrypted. Sensitive data at rest is vulnerable to unauthorized access if the underlying storage is compromised.',
    severity: 'high',
    category: 'missing_encryption',
    status: 'pending',
    affectedResource: {
      id: 'vol-0123456789',
      type: 'ebs',
      name: 'db-primary-data',
      region: 'us-east-1',
    },
    recommendation: 'Enable EBS encryption for all volumes containing sensitive data. Create encrypted snapshots and restore to new encrypted volumes.',
    details: [
      'Volume size: 500 GB',
      'Attached to: i-0m1n2o3p4q5r (DB-Primary)',
      'Contains database files',
    ],
    riskScore: 78,
  },
  {
    id: 'sec-004',
    title: 'Public S3 Bucket Detected',
    description: 'S3 bucket has public read access enabled. Any data stored in this bucket can be accessed by anyone on the internet without authentication.',
    severity: 'high',
    category: 'public_exposure',
    status: 'pending',
    affectedResource: {
      id: 'my-app-assets',
      type: 's3',
      name: 'my-app-assets',
      region: 'us-east-1',
    },
    recommendation: 'Review bucket policy and ACLs. Remove public access unless explicitly required. Enable S3 Block Public Access settings.',
    details: [
      'Bucket ACL: public-read',
      'Block Public Access: Disabled',
      'Contains 1,234 objects',
    ],
    riskScore: 85,
  },
  {
    id: 'sec-005',
    title: 'Database Port Exposed Beyond VPC',
    description: 'PostgreSQL port (5432) is accessible from outside the VPC. Database should only be accessible from application tier within the same VPC.',
    severity: 'high',
    category: 'network',
    status: 'pending',
    affectedResource: {
      id: 'sg-0a3b4c5d',
      type: 'security_group',
      name: 'DB-Tier',
      region: 'us-east-1',
    },
    recommendation: 'Restrict database access to only the application security group. Remove any 0.0.0.0/0 or wide CIDR ranges.',
    details: [
      'Port 5432 accessible from 10.0.0.0/8',
      'Should be restricted to sg-0f2e1d4c only',
    ],
    riskScore: 75,
  },
  {
    id: 'sec-006',
    title: 'IAM Role with Excessive Permissions',
    description: 'Lambda execution role has AdministratorAccess policy attached. This violates the principle of least privilege.',
    severity: 'medium',
    category: 'overly_permissive',
    status: 'pending',
    affectedResource: {
      id: 'lambda-execution-role',
      type: 'iam_role',
      name: 'lambda-execution-role',
      region: 'global',
    },
    recommendation: 'Create a custom IAM policy with only the specific permissions needed for the Lambda function to operate.',
    details: [
      'Policy: AdministratorAccess',
      'Used by: process-orders, send-notifications',
      'Last used: 2 hours ago',
    ],
    riskScore: 65,
  },
  {
    id: 'sec-007',
    title: 'Missing VPC Flow Logs',
    description: 'VPC does not have flow logs enabled. Network traffic is not being monitored, making it difficult to detect suspicious activity or troubleshoot connectivity issues.',
    severity: 'medium',
    category: 'compliance',
    status: 'pending',
    affectedResource: {
      id: 'vpc-0a1b2c3d',
      type: 'vpc',
      name: 'Production VPC',
      region: 'us-east-1',
    },
    recommendation: 'Enable VPC Flow Logs and send to CloudWatch Logs or S3 for analysis and compliance requirements.',
    details: [
      'No flow logs configured',
      'Recommended for PCI-DSS, HIPAA compliance',
    ],
    riskScore: 55,
  },
  {
    id: 'sec-008',
    title: 'Outdated SSL/TLS Configuration',
    description: 'Load balancer is configured to accept TLS 1.0 and TLS 1.1 connections. These protocols have known vulnerabilities.',
    severity: 'medium',
    category: 'weak_authentication',
    status: 'pending',
    affectedResource: {
      id: 'alb-web-frontend',
      type: 'elb',
      name: 'web-frontend-alb',
      region: 'us-east-1',
    },
    recommendation: 'Update security policy to only allow TLS 1.2 and TLS 1.3. Use AWS predefined security policies like ELBSecurityPolicy-TLS-1-2-2017-01.',
    details: [
      'TLS 1.0: Enabled',
      'TLS 1.1: Enabled',
      'TLS 1.2: Enabled',
    ],
    riskScore: 50,
  },
  {
    id: 'sec-009',
    title: 'Default VPC In Use',
    description: 'Resources are deployed in the default VPC. Default VPCs have less restrictive default security settings.',
    severity: 'low',
    category: 'compliance',
    status: 'pending',
    affectedResource: {
      id: 'vpc-default',
      type: 'vpc',
      name: 'Default VPC',
      region: 'us-east-1',
    },
    recommendation: 'Migrate resources to a custom VPC with properly configured network ACLs and security groups.',
    details: [
      '3 EC2 instances in default VPC',
      '2 RDS instances in default VPC',
    ],
    riskScore: 35,
  },
  {
    id: 'sec-010',
    title: 'Missing Resource Tags',
    description: 'Several resources are missing required tags for cost allocation and security auditing.',
    severity: 'low',
    category: 'compliance',
    status: 'pending',
    affectedResource: {
      id: 'i-0a1b2c3d4e5f',
      type: 'ec2',
      name: 'App-Worker-1',
      region: 'us-east-1',
    },
    recommendation: 'Add required tags: Environment, Owner, CostCenter, Application for all resources.',
    details: [
      'Missing: Environment tag',
      'Missing: Owner tag',
      'Missing: CostCenter tag',
    ],
    riskScore: 25,
  },
];

export const SEVERITY_FILTER_TABS = [
  { key: 'all', label: 'All Issues' },
  { key: 'critical', label: 'Critical' },
  { key: 'high', label: 'High' },
  { key: 'medium', label: 'Medium' },
  { key: 'low', label: 'Low' },
] as const;

export const SEVERITY_COLORS: Record<string, string> = {
  critical: '#dc2626',
  high: '#ea580c',
  medium: '#d97706',
  low: '#65a30d',
};

export const SEVERITY_LABELS: Record<string, string> = {
  critical: 'Critical',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
};

export const CATEGORY_LABELS: Record<string, string> = {
  overly_permissive: 'Over-Permissive',
  missing_encryption: 'Missing Encryption',
  public_exposure: 'Public Exposure',
  weak_authentication: 'Weak Authentication',
  compliance: 'Compliance',
  network: 'Network',
};
